#! /bin/bash

# install gems without needing root
export GEM_HOME="$HOME/gems"
export PATH="$GEM_HOME/bin:$PATH"

# install Jekyll
gem install jekyll -v 3.7.3

# build the lesson website
ls gems
make site
